version: '3.8'

services:
  app:
    container_name: vacancies-parsing
    build:
      context: .
      dockerfile: docker/Dockerfile.php
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
      - composer-cache:/tmp/composer-cache
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      TZ: ${TZ:-Europe/Moscow}
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    stdin_open: true
    tty: true
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  composer-cache:
    driver: local
